var require = {
    waitSeconds: 0,
    paths: {
        // vendor dependencies
        'jquery': '../bower_components/jquery/dist/jquery.min',
        'bootstrap': '../bower_components/bootstrap/dist/js/bootstrap.min',
        'angular': '../bower_components/angular/angular.min',
        'angular-animate': '../bower_components/angular-animate/angular-animate.min',
        'angular-aria': '../bower_components/angular-aria/angular-aria.min',
        'angular-messages': '../bower_components/angular-messages/angular-messages.min',
        'angular-material': '../bower_components/angular-material/angular-material.min',
        'angular-ui-router': '../bower_components/angular-ui-router/release/angular-ui-router.min',
        'angular-bootstrap': '../bower_components/angular-bootstrap/ui-bootstrap-tpls.min',
        'angular-couch-potato': '../bower_components/angular-couch-potato/dist/angular-couch-potato',
        'angular-cookies': '../bower_components/angular-cookies/angular-cookies',
        'angular-resource': '../bower_components/angular-resource/angular-resource.min',
        'angular-sanitize': '../bower_components/angular-sanitize/angular-sanitize.min',
        'angular-translate': '../bower_components/angular-translate/angular-translate.min',
        'angular-translate-loader-partial': '../bower_components/angular-translate-loader-partial/angular-translate-loader-partial.min',
        'domReady': '../bower_components/requirejs-domready/domReady',
        'jquery-datatables': '../bower_components/datatables/media/js/jquery.dataTables.min',
        'angular-datatables': '../bower_components/angular-datatables/dist/angular-datatables',
        'angular-datatables.bootstrap': '../bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap',
        'angular-datatables.colreorder': '../bower_components/angular-datatables/dist/plugins/colreorder/angular-datatables.colreorder',
        'angular-datatables.columnfilter': '../bower_components/angular-datatables/dist/plugins/columnfilter/angular-datatables.columnfilter',
        'angular-datatables.light-columnfilter': '../bower_components/angular-datatables/dist/plugins/light-columnfilter/angular-datatables.light-columnfilter',
        'angular-datatables.colvis': '../bower_components/angular-datatables/dist/plugins/colvis/angular-datatables.colvis',
        'angular-datatables.fixedcolumns': '../bower_components/angular-datatables/dist/plugins/fixedcolumns/angular-datatables.fixedcolumns',
        'angular-datatables.fixedheader': '../bower_components/angular-datatables/dist/plugins/fixedheader/angular-datatables.fixedheader',
        'angular-datatables.scroller': '../bower_components/angular-datatables/dist/plugins/scroller/angular-datatables.scroller',
        'angular-datatables.tabletools': '../bower_components/angular-datatables/dist/plugins/tabletools/angular-datatables.tabletools',
        'angular-datatables.buttons': '../bower_components/angular-datatables/dist/plugins/buttons/angular-datatables.buttons',
        'angular-datatables.select': '../bower_components/angular-datatables/dist/plugins/select/angular-datatables.select',

        'charts': '../bower_components/Chart.js/Chart',
        'angular-chart': '../bower_components/angular-chart.js/dist/angular-chart',
        'chartist': '../bower_components/chartist/dist/chartist.min',

        'mobile-detect': '../bower_components/mobile-detect/mobile-detect',
        'moment': '../bower_components/moment/moment',
        'perfect-scrollbar': '../bower_components/perfect-scrollbar/js/perfect-scrollbar',
        'toastr': '../bower_components/toastr/toastr',

        'lodash': '../bower_components/lodash/lodash',
        'angular-simple-logger': '../bower_components/angular-simple-logger/dist/angular-simple-logger.min',
        'angular-google-maps': '../bower_components/angular-google-maps/dist/angular-google-maps.min',

        // core app dependencies
        'core.module': 'core/core.module',
        'core.config': 'core/core.config',
        'core.run': 'core/core.run',
        'api-resolver.service': 'core/services/api-resolver.service',
        'ms-api.provider': 'core/services/ms-api.provider',
        'ms-utils.service': 'core/services/ms-utils.service',
        'ms-card.directive': 'core/directives/ms-card/ms-card.directive',
        'ms-datepicker-fix.directive': 'core/directives/ms-datepicker-fix/ms-datepicker-fix.directive',
        'ms-form-wizard.directive': 'core/directives/ms-form-wizard/ms-form-wizard.directive',
        'ms-material-color-picker.directive': 'core/directives/ms-material-color-picker/ms-material-color-picker.directive',
        'ms-nav.directive': 'core/directives/ms-nav/ms-nav.directive',
        'ms-navigation.directive': 'core/directives/ms-navigation/ms-navigation.directive',
        'ms-random-class.directive': 'core/directives/ms-random-class/ms-random-class.directive',
        'ms-responsive-table.directive': 'core/directives/ms-responsive-table/ms-responsive-table.directive',
        'ms-scroll.directive': 'core/directives/ms-scroll/ms-scroll.directive',
        'ms-search-bar.directive': 'core/directives/ms-search-bar/ms-search-bar.directive',
        'ms-sidenav-helper.directive': 'core/directives/ms-sidenav-helper/ms-sidenav-helper.directive',
        'ms-splash-screen.directive': 'core/directives/ms-splash-screen/ms-splash-screen.directive',
        'ms-stepper.directive': 'core/directives/ms-stepper/ms-stepper.directive',
        'ms-timeline': 'core/directives/ms-timeline/ms-timeline',
        'ms-widget.directive': 'core/directives/ms-widget/ms-widget.directive',
        'highlight.directive': 'core/directives/highlight.directive',
        'fuse-generator.factory': 'core/theming/fuse-generator.factory',
        'fuse-palettes.constant': 'core/theming/fuse-palettes.constant',
        'fuse-themes.constant': 'core/theming/fuse-themes.constant',
        'fuse-theming.config': 'core/theming/fuse-theming.config',
        'fuse-theming.provider': 'core/theming/fuse-theming.provider',
        'theme-options.directive' : 'core/theme-options/theme-options.directive',
        'basic.filter': 'core/filters/basic.filter',
        'tag.filter': 'core/filters/tag.filter',
        'fuse-config.provider': 'core/config/fuse-config.provider',

        'navigation.module': 'navigation/navigation.module',
        'navigation.controller': 'navigation/navigation.controller',

        'toolbar.module': 'toolbar/toolbar.module',
        'toolbar.controller': 'toolbar/toolbar.controller',

        'quick-panel.module': 'quick-panel/quick-panel.module',
        'quick-panel.controller': 'quick-panel/quick-panel.controller',
        'chat-tab.controller': 'quick-panel/tabs/chat/chat-tab.controller',

        // app core modules dependencies
        'modules.controller': 'modules/modules.controller',

        'core.modules': 'modules/core/core.modules',

        'sample.module': 'modules/core/sample/sample.module',
        'sample.controller': 'modules/core/sample/sample.controller',

        'maps.module': 'modules/core/maps/maps.module',
        'maps.controller': 'modules/core/maps/maps.controller',

        // app custom modules dependencies

        // app index dependencies
        'index.api': 'index/index.api',
        'index.config': 'index/index.config',
        'index.constants': 'index/index.constants',
        'index.controller': 'index/index.controller',
        'index.route': 'index/index.route',
        'index.run': 'index/index.run',
        'index.module': 'index/index.module'
    },
    shim: {
        // vendor dependencies
        'bootstrap': { deps: ['jquery'] },
        'jquery-datatables': { deps: ['jquery'] },
        'angular': {'exports': 'angular', deps: ['jquery']},
        'angular-animate': { deps: ['angular'] },
        'angular-aria': { deps: ['angular'] },
        'angular-messages': { deps: ['angular'] },
        'angular-material': { deps: ['angular'] },
        'angular-bootstrap': { deps: ['angular'] },
        'angular-ui-router': { deps: ['angular'] },
        'angular-cookies': { deps: ['angular'] },
        'angular-resource': { deps: ['angular'] },
        'angular-sanitize': { deps: ['angular'] },
        'angular-translate': { deps: ['angular'] },
        'angular-translate-loader-partial': { deps: ['angular-translate'] },
        'angular-couch-potato': { deps: ['angular'] },
        'angular-datatables': { deps: ['angular', 'jquery-datatables'] },
        'angular-datatables.bootstrap': { deps: ['angular-datatables'] },
        'angular-datatables.colreorder': { deps: ['angular-datatables'] },
        'angular-datatables.columnfilter': { deps: ['angular-datatables'] },
        'angular-datatables.light-columnfilter': { deps: ['angular-datatables'] },
        'angular-datatables.colvis': { deps: ['angular-datatables'] },
        'angular-datatables.fixedcolumns': { deps: ['angular-datatables'] },
        'angular-datatables.fixedheader': { deps: ['angular-datatables'] },
        'angular-datatables.scroller': { deps: ['angular-datatables'] },
        'angular-datatables.tabletools': { deps: ['angular-datatables'] },
        'angular-datatables.buttons': { deps: ['angular-datatables'] },
        'angular-datatables.select': { deps: ['angular-datatables'] },

        'angular-simple-logger': { deps: ['angular'] },
        'angular-google-maps': { deps: ['angular', 'lodash', 'angular-simple-logger'] },

        // core app dependencies
        'core.module': { deps: ['angular']},
        'core.config': { deps: ['core.module']},
        'core.run':  { deps: ['core.module']},
        'api-resolver.service': { deps: ['core.module']},
        'ms-api.provider': { deps: ['core.module']},
        'ms-utils.service': { deps: ['core.module']},
        'ms-card.directive':  { deps: ['core.module']},
        'ms-datepicker-fix.directive':  { deps: ['core.module']},
        'ms-form-wizard.directive':  { deps: ['core.module']},
        'ms-material-color-picker.directive':  { deps: ['core.module']},
        'ms-nav.directive':  { deps: ['core.module']},
        'ms-navigation.directive':  { deps: ['core.module']},
        'ms-random-class.directive':  { deps: ['core.module']},
        'ms-responsive-table.directive':  { deps: ['core.module']},
        'ms-scroll.directive':  { deps: ['core.module']},
        'ms-search-bar.directive':  { deps: ['core.module']},
        'ms-sidenav-helper.directive':  { deps: ['core.module']},
        'ms-splash-screen.directive':  { deps: ['core.module']},
        'ms-stepper.directive':  { deps: ['core.module']},
        'ms-timeline':  { deps: ['core.module']},
        'ms-widget.directive':  { deps: ['core.module']},
        'highlight.directive':  { deps: ['core.module']},
        'fuse-generator.factory':  { deps: ['core.module']},
        'fuse-palettes.constant': { deps: ['core.module']},
        'fuse-themes.constant': { deps: ['core.module']},
        'fuse-theming.config': { deps: ['core.module']},
        'fuse-theming.provider': { deps: ['core.module']},
        'theme-options.directive': { deps: ['core.module']},
        'basic.filter': { deps: ['core.module']},
        'tag.filter': { deps: ['core.module']},
        'fuse-config.provider': { deps: ['core.module']},

        'navigation.module': { deps: ['angular']},
        'navigation.controller': { deps: ['navigation.module']},

        'toolbar.module': { deps: ['angular']},
        'toolbar.controller': { deps: ['toolbar.module']},

        'quick-panel.module': { deps: ['angular']},
        'quick-panel.controller': { deps: ['quick-panel.module']},
        'chat-tab.controller': { deps: ['quick-panel.module']},

        // app core modules dependencies
        'modules.controller': { deps: ['index.module']},

        'core.modules': { deps: ['maps.module']},

        'sample.module': { deps: ['angular']},
        'sample.controller': { deps: ['sample.module']},

        'maps.module': { deps: ['angular']},
        'maps.controller': { deps: ['maps.module']},

        // app custom modules dependencies

        // app index dependencies
        'index.module': { deps: ['angular',
                                 'core.module',
                                 'navigation.module',
                                 'toolbar.module',
                                 'quick-panel.module',
                                 //'core.modules',
                                 'sample.module']},
        'index.api': { deps: ['index.module']},
        'index.config': { deps: ['index.module']},
        'index.constants': { deps: ['index.module']},
        'index.controller': { deps: ['index.module']},
        'index.route': { deps: ['index.module']},
        'index.run': { deps: ['index.module']}
    },
    priority: [
        'jquery',
        'bootstrap',
        'angular'
    ]
};
